### PR TITLE
Fantastic Features

### PR DESCRIPTION
**Pull request by ingalls**
### Context

- Completely rework UI based error handling into a single error handling component
- Move more UI API calls into the standard hecate library
- Add support for loading the server schema at load time
- Add support for displaying schema descriptions in the features panel

Screenshot from 2019-07-16 23-54-16

cc/ @ingalls

### CODE REVIEW

**Comment by ingalls** [comment]
- Add support for optionally loading the feature history into the UI

Screenshot from 2019-07-17 00-57-02

**Comment by ingalls** [comment]
- It's a bit rough around the edges, but display the loaded history

Screenshot from 2019-07-17 01-07-57

**Comment by ingalls** [comment]
Closes: https://github.com/mapbox/Hecate/issues/54

**Review by samely — APPROVED** [review]
LGTM! :taco:

**Pull request merged**
